// <auto-generated />
namespace EF_CODEFIRST_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddQualityNotNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddQualityNotNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202606201100088_AddQualityNotNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
